replicaCount: 1

image:
  repository: bartoszduch/my-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
serviceAccount:
  create: true
  annotations: {}
  name: ""
ingress:
  enabled: false  # Change this to `true` if you want to use ingress.
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 500m
  requests:
    cpu: 200m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
